### ISSUE TITLE
[FEATURE REQUEST] UTF-8 Encoding issue

### ISSUE THREAD

**Issue by djshadow** [GinoPane/wn-blogtaxonomy-plugin#1]
Hi, I tried to create a new series, and when I entered my title, it contains ' and I got an error that I can't use characters like that. Can something be done about that, please?

**Comment by GinoPane** [comment]
The "'" is definitely supported, but the update here is that it would be nice to support "[]" characters.

**Comment by GinoPane** [comment]
I extended character sets in 3.6.0
