### ISSUE TITLE
SQLSTATE[42S02] Base table or view not found

### ISSUE THREAD

**Issue by djshadow** [GinoPane/wn-blogtaxonomy-plugin#2]
**Describe the bug**
After adding the plugin, when you open it at the backend you get SQLSTATE[42S02]: Base table or view not found: 1146 Table ' .ginopane_blogtaxonomy_tags' doesn't exist (SQL: select count(*) as aggregate from ginopane_blogtaxonomy_tags)
....... Connection.php line 669

**To Reproduce**
1. composer require ginopane/wn-blogtaxonomy-plugin
2.Go to backend/system/settings/update/ginopane/blogtaxonomy/settings
3.Enable Post type and Enable images for categories and save and close.
4.Click on the blog tab

**Expected behavior**
Blog tab should have loaded but that's when the error screen shows.

**Additional context**
The quick fix so far is you have run this in your console
PHP artisan plugin:refresh ginopane.blogtaxonomy

Then the error will be solved.

**Comment by GinoPane** [comment]
Yes, as discussed, I'll add this into README. Not sure I could do anything else to fix this. Worth checking with WinterCMS core guys.

**Comment by GinoPane** [comment]
I updated the README in 3.6.0 version. The behavior is totally expected.
